### ISSUE TITLE
getPAgeReference()

### ISSUE THREAD

**Issue by hridayam** [nopenoway0/CS149#32]
This function in page_operations.c follows the formula provided in the preview for when the process has 11 pages. But what about when there are only 5 pages or 31 pages. Maybe I'm just confused but is the page size fixed or am I making a mistake?

**Comment by ravuthlong** [comment]
I thought the change number is fixed. For example, there's 70% chance the next change is -1, 0 or 1.
This means that no matter what the process page size is there is always 70% chance, thus 0->7 would represent that 70% chance already.

**Comment by hridayam** [comment]
yes that makes sense. stupid question. my bad

**Comment by benj-G** [comment]
Not a stupid question at all. I was also wondering about this, but now it makes sense

**Comment by ravuthlong** [comment]
Ben, we need to use the thread and mutex for this too, right? Because the processes run at the same time?

**Comment by benj-G** [comment]
We could or we could just run on 1 thread and jump from process to process. It would be simpler that way
