### ISSUE TITLE
FIFO won't make in page operations

### ISSUE THREAD

**Issue by nopenoway0** [nopenoway0/CS149#33]
made some key changes to some functions in page operations. The result is fifo won't compile. If you need to compile without fifo, remove FIFO.o from the make file and it should run correctly.

**Comment by ravuthlong** [comment]
just comment my code out if you're pushing soon or i can do it

**Comment by nopenoway0** [comment]
Yup I changed the makefile. Made changes, adding a page should be simple and mostly work
