### ISSUE TITLE
Time type

### ISSUE THREAD

**Issue by ravuthlong** [nopenoway0/CS149#39]
Maybe it's easier for quanta and completion time to all be in milliseconds?

Process makes a reference every 100ms (0.1 s). We currently have completion_time as second so we'd have to subtract 0.1 from that every time a process makes a reference, so we'd have to change the type of completition_time to double.

Instead, we can think of everything as ms, so we can set up the randomly generated completion time of 1, 2, 3, 4, 5 as 1000, 2000, 3000, 4000, 5000 instead? Quanta would increment in the unit of 100ms..?

**Comment by nopenoway0** [comment]
since the smallest unit is 100ms, why don't we make the time 100ms = 1 quanta. Then completion time would be 10, 20, 30, 40, 50?

**Comment by ravuthlong** [comment]
yes, you are right. that'd be easier. Math .-.

**Comment by ravuthlong** [comment]
bugfixes branch updated.
